import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, Clock, MapPin } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { StatusPill } from "@/components/glam-ui";
import type { BookingStatus } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/bookings/")({ component: BookingsPage });
type Booking = { id: string; artistName: string; service: string; date: string; time: string; location: string; total: number; status: BookingStatus };
const groups: Record<"Upcoming" | "Completed" | "Cancelled", BookingStatus[]> = { Upcoming: ["PENDING", "ACCEPTED", "CONFIRMED"], Completed: ["COMPLETED"], Cancelled: ["CANCELLED", "REJECTED"] };
const inr = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);

function BookingsPage() { const [tab, setTab] = useState<keyof typeof groups>("Upcoming"); const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { void fetch("/api/bookings").then(async (response) => { const data = await response.json() as { bookings?: Booking[]; error?: string }; if (!response.ok) throw new Error(data.error); setBookings(data.bookings ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Could not load bookings.")).finally(() => setLoading(false)); }, []); const list = useMemo(() => bookings.filter((booking) => groups[tab].includes(booking.status)), [bookings, tab]); return <AppShell title="My bookings" subtitle="Appointments and payments"><div className="flex gap-1 rounded-2xl bg-muted p-1">{Object.keys(groups).map((group) => <button key={group} onClick={() => setTab(group as keyof typeof groups)} className={cn("flex-1 rounded-xl py-2 text-sm font-semibold", tab === group ? "bg-card text-foreground shadow-soft" : "text-muted-foreground")}>{group}</button>)}</div>{loading && <p className="surface mt-4 text-sm text-muted-foreground">Loading bookings…</p>}{error && <p className="surface mt-4 text-sm text-destructive">{error}</p>}<div className="mt-4 flex flex-col gap-3">{list.map((booking) => <div key={booking.id} className="surface p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{booking.service}</h3><p className="text-xs text-muted-foreground">with {booking.artistName}</p></div><StatusPill status={booking.status} /></div><div className="mt-3 grid gap-1.5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><CalendarDays className="size-3.5" />{booking.date}</span><span className="flex items-center gap-2"><Clock className="size-3.5" />{booking.time}</span><span className="flex items-center gap-2"><MapPin className="size-3.5" />{booking.location}</span></div><div className="mt-3 flex items-center justify-between border-t pt-3"><span className="text-sm font-semibold">{inr(booking.total)}</span><Link to="/bookings/$bookingId" params={{ bookingId: booking.id }} className="rounded-full bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground">View details</Link></div></div>)}</div>{!loading && !error && list.length === 0 && <p className="py-12 text-center text-sm text-muted-foreground">Nothing here yet.</p>}</AppShell>; }
